cloudscape-design/browser-test-tools

src/browsers/capabilities.ts

*Issue #, if available:* N/A
*Description of changes:* Safari tests seem to be timing out. Temporary stopgap while we investigate any underlying causes.

chore: Increase the idle timeout for Safari to 180s

---

src/use-browser.ts
test/use-browser.test.js

Add `enableBrowserErrors` option to allow test runners to not fail on browser errors 

feat: Add config to disable test failing on browser errors

---

src/browser-scripts/live-announcements.ts
src/page-objects/base.ts
test/fixtures/test-page-object.html
test/page-object.test.js

This util was first introduced in the board components to test against live announcements issued on the page, see: https://github.com/cloudscape-design/board-components/blob/main/test/functional/board-layout/live-announcements.test.ts.
Adding this util here would allow to reuse it for other projects. 

feat: Add live announcements util to base page

---

src/page-objects/full-page-screenshot.ts

The current max page size for the screenshots is out of date (reduced from 20000 to 16000). This PR updates it.
There is also a corresponding [PR](https://github.com/cloudscape-design/components/pull/777) for components, as these values should be kept in sync.

chore: Update screenshot max page height

---

src/page-objects/base.ts
test/fixtures/test-page-object.html
test/page-object.test.js

Added `page.isClickable('.selector')` method to reuse across tests
Tried `element.isEnabled()` too, but it is not very universal (does not consider `pointer-events: none`, which we use for disabled buttons with hrefs). `isClickable` covers more cases

feat: add isClickable method

---

src/page-objects/utils.ts
test/page-object.test.js

So far, the iOS screenshot utils assume that the Safari navigation bar is at the top of the screen and therefore needs to be cut out of every screenshot. This is no longer the case starting with iOS 15.
This change removes the need for considering the navigation bar and therefore adds support for iOS 15 and drops support for iOS 14 and below.

feat: Update iOS screenshots to only support iOS 15+

---

src/browsers/capabilities.ts

Currently local Safari run fails with this error: `Illegal key values seen in w3c capabilities: [idleTimeout] Make sure to add vendor prefix like "goog:", "appium:", "moz:", etc to non W3C capabilities.`
This config is non-standard and Selenium declines such request.
---

fix: Remove idleTimeout capability from local Safari config

---

__mocks__/aws-sdk/clients/devicefarm.js
package-lock.json
package.json
src/browsers/browser-creator.ts
src/browsers/browserstack.ts
src/browsers/capabilities.ts
src/browsers/devicefarm-mobile.ts
src/browsers/devicefarm.ts
src/browsers/local.ts
src/page-objects/base.ts
test/browser.test.ts
test/browsers/browserstack.test.ts
test/browsers/devicefarm-mobile.test.ts
test/browsers/devicefarm.test.ts
test/browsers/wdio-mock.ts
test/compare-images.test.ts
test/full-page-screenshot.test.ts
test/image-utils.test.ts
test/page-object.test.ts
test/use-browser.test.ts
test/utils/config.ts
test/utils/setup-local-driver.ts
test/utils/start-chromedriver.ts
test/utils/stop-chromedriver.ts
tsconfig.test.json

Un-revert https://github.com/cloudscape-design/browser-test-tools/pull/54 and fix the previous issue
There was a dependency issue with `@wdio/types`. This is transitive dependency, we cannot rely on it directly, because it may not exist.
Updated the code to use only `webdriverio` typings

chore: Convert tests to typescript

---

src/browsers/browser-creator.ts
test/browsers/devicefarm-mobile.test.ts
test/browsers/wdio-mock.ts

Reverts cloudscape-design/browser-test-tools#57.
The API doesn't actually do what we thought it did :(

chore: Revert: Make sure the iOS Safari tab bar is always at the bottom

---

src/browsers/local.ts

It got accidentally removed there https://github.com/cloudscape-design/browser-test-tools/commit/b0610161ec99fd2eb50ba125740e3133ae719a5c#diff-94fbee9f84ac61415e3ab21504c0d7e598384a284f3b86acb41128a6f0b21c89L9, let's bring this back

fix: add missing browsers to local run configuration

---

package.json
src/page-objects/utils.ts
test/utils/start-chromedriver.ts

*Issue #, if available:* AWSUI-22318
*Description of changes:* Starting with NodeJS 17, the default DNS name resolution now favors IPv6 over IPv4 addresses. This means that "localhost" now resolves to `::1` instead of `127.0.0.1`. This causes some compatibility issues with the local dev server, as well as the local Chrome/puppeteer debugger address.
This PR changes the algorithm back to favor IPv4 addresses.
See this green Draft PR using NodeJS 18 in all GitHub workflows: https://github.com/cloudscape-design/browser-test-tools/pull/66.

fix: Fix localhost address resolution in NodeJS 17+

---

test/full-page-screenshot.test.ts

Fixing this issue: https://github.com/cloudscape-design/components/actions/runs/6868817322/attempts/9
There is a compatibility between webdriverio v7 and node.js 18: https://github.com/webdriverio/webdriverio/issues/8279 (we should upgrade to v8, really).
We already applied a workaround: https://github.com/cloudscape-design/browser-test-tools/pull/67 However it was not covering this test, because we called `browser.getPuppeteer` directly. Swapping with a utility makes it more stable (I think)

chore: Fix full page screenshot test issue

---

package-lock.json
package.json
test/browser.test.ts
test/browsers/browserstack.test.ts
test/browsers/devicefarm-mobile.test.ts
test/browsers/devicefarm.test.ts
test/browsers/wdio-mock.ts
test/compare-images.test.ts
test/full-page-screenshot.test.ts
test/image-utils.test.ts
test/page-object.test.ts
test/use-browser.test.ts
test/utils/global-setup.ts
test/utils/setup-local-driver.ts
test/utils/stop-chromedriver.ts
tsconfig.json
tsconfig.test.json
vite.config.ts

As per the title this migrates from jest to vitest. There's a very small performance gain but for the most part its just to start to modernise the package a bit. Jest still lacks support for esm natively and relies then on ts-jest to run. This just works out of the box with vitest. We have already migrated a few of our other packages and so this also aligns with those.

chore: Migrate to vitest

---

package-lock.json
package.json
src/chrome-launcher.ts

Fix flaky tests caused by `startWebdriver` promise resolving too early before chrome driver is ready to accept tests

fix: wait on chromdriver port before starting tests

---

vite.config.mts

* Fix [this build issue](https://github.com/cloudscape-design/components/actions/runs/9684655320/job/26722947216?pr=2419). We already have 60 seconds config on all our other repositories, let's follow the suite here too
* Rename the config file to address this deprecation warning: "The CJS build of Vite's Node API is deprecated"

chore: Increase test timeout

---

src/page-objects/full-page-screenshot.ts
src/page-objects/screenshot.ts

This pull request adds an optional parameter to forcibly bypass puppeteer and use the `scollAndMergeStrategy` to perform screenshot tests. This was added to support the conditional use of `scollAndMergeStrategy` when taking RTL screenshots in Chrome.

chore: Add an optional parameter to bypass puppeteer

---

package-lock.json
package.json

*Issue #, if available:* [dependabot alert](https://github.com/cloudscape-design/browser-test-tools/security/dependabot/21)
[Previous attempt](https://github.com/cloudscape-design/browser-test-tools/pull/92) was reverted because dependencies were not in NPMPM yet.

chore: Bump fast-xml-parser and @aws-sdk/client-device-farm

---

src/browsers/browserstack.ts
test/browsers/browserstack.test.ts

Self-explanatory. Use https, because it is better
Deployed to my dev-pipeline and got a green browserstack test run

fix: Use https to access browserstack

---

src/browsers/capabilities.ts

*Description of changes:* New version of chrome set headless to "new" which caused problems in tests. Temporarily, setting it to "old" to unblock tests.

fix: Temporarily set chrome headless mode to old

---

src/browsers/browser-creator.ts
test/browsers/browserstack.test.ts

Changing default browser height to a bigger value to make issues with element out of screen less likely.
This is especially helpful when migrating to Chromium --headless=new because it makes window inner height smaller than the given browser height setting, see: https://github.com/cloudscape-design/browser-test-tools/pull/105.

feat: Change default browser height from 604px to 800px

---

src/browsers/capabilities.ts
src/use-browser.ts
test/page-object.test.ts
test/use-browser.test.ts

Migrating to Chromium new headless mode: https://developer.chrome.com/docs/chromium/headless
There are two observer side effects:
* The window.innerHeight is smaller than the height set with useBrowser or setWindowSize setting by 87px. The problem might be solved if migrating to the newer WebdriverIO. For now, the tests are updated to tolerate the height setting as a range.
* When there is a missing favicon on the test page or it cannot be downloaded, the new Chromium adds an error to the console. These errors are then ignored as non-severe as otherwise any error in the console log makes the test fail.

chore: Use chromium headless=new mode

---

src/browsers/capabilities.ts

Reapplying #120 after `CR-169538412` has been merged and run through the pipeline.
Full doc for reference: `wldmA5MyTGS5`
Issue: `AWSUI-59983`
This reverts commit c9a9db9f8cad837d21bad7b9b66927c38964b3c4, which in turn reverted be1476baf6858391b689c345e566c5bdf28e2be7 (thus reapplying the latter).
Tested in my pipeline.

chore: Show scrollbars in Chrome-based integration tests

---

package-lock.json
package.json
src/browsers/browser-creator.ts
src/browsers/browserstack.ts
src/browsers/capabilities.ts
src/browsers/devicefarm-mobile.ts
src/browsers/devicefarm.ts
src/browsers/local.ts
src/page-objects/base.ts
src/page-objects/full-page-screenshot.ts
src/use-browser.ts
tsconfig.json

Upgraded WebdriverIO from v7 to v9.
See: [ygtJAKJyEnsh] and CR-167061092.

chore: Upgrades WebdriverIO to v9

---

src/browsers/local.ts

Fixes the error in internal tests: `Error: WebDriver Bidi command "browsingContext.navigate" failed with error: unknown error - Error: NS_BINDING_ABORTED`

fix: Enforces webdriver classic in Firefox

---

test/compare-images.test.ts

Fix this issue
* https://github.com/cloudscape-design/browser-test-tools/actions/runs/13395611620/job/37413745957
* https://github.com/cloudscape-design/browser-test-tools/actions/runs/13394431162/job/37409756107
* https://github.com/cloudscape-design/browser-test-tools/actions/runs/13395862211/job/37414587509
Downloaded the diff screenshot from these tests, figured it is a scrollbar fading animation after page refresh

chore: Fix flaky test

---

src/browsers/browserstack.ts

Since Safari 18 is out, 16 is now our oldest officially supported version.
Ticket: `AWSUI-60431`
Tested in my pipeline.

chore: Upgrade Safari to version 16

---

src/browsers/browserstack.ts

Reverts cloudscape-design/browser-test-tools#135
There are some unexpected failures in the pipeline. Let's revert to unblock it and investigate.

revert: Revert "chore: Upgrade Safari to version 16"

---

src/browser-scripts/scroll.ts
src/page-objects/base.ts
src/page-objects/screenshot.ts
test/fixtures/test-page-object.html
test/page-object.test.ts

Make sure that we attempt to scroll an element which is actually scrollable

feat: Validate if an element to scroll is actually scrollable

---

package-lock.json
package.json

*Description of changes:* axios dependency is coming from wait-on. It is a major version bump but the only [breaking change](https://github.com/jeffbski/wait-on/releases) is for unix socket url which we don't use

chore: Upgrade 'wait-on'

---

package-lock.json
package.json

Updating the wait-on package to resolve security vulnerability with axios that is a dependency of it.
Update: the axios was apparently upgraded by dependabot already: https://github.com/cloudscape-design/browser-test-tools/pull/142. Nevertheless, I think we can update the wait-on so that older axios is not re-installed.

chore: Update wait-on version

---

src/browsers/browser-creator.ts

The current value of 4 minutes wait time is unreasonable, because we have the total test timeout of 1 min in most places, like here for example: https://github.com/cloudscape-design/components/blob/1efbf47ce37330f36174b0ccecce8aa40e8f20a6/jest.integ.config.js#L18
The first step is to make it configurable, then apply custom very long configuration only to the use-case where it is really needed and then update the default to something more useful.

feat: make connectionRetryTimeout configurable
