- src/browsers/browserstack.ts
> chore: Use latest Safari in BrowserStack

- package-lock.json
- package.json
> chore: Downgrade aws-sdk

- src/page-objects/base.ts
This should help with some unstable screenshot states
> Add a delay after scrolling

- src/use-browser.ts
- test/use-browser.test.js
make it easier to see errors in console when they happen
> include console errors into exception message

- package-lock.json
- package.json
AWSUI-19722
- Regenerate package-lock
> chore: Upgrade to Node16

- test/full-page-screenshot.test.js
This test is flaky and it disturbs build for our components repo.
Also see #29 for some attempts to investigate this. Since even when the test passes, it does not produce the expected results, we will disable it, because it does not add confidence
---
> chore: Disable flaky test

- package-lock.json
- package.json
This reverts commit 90e862840106f4be3af59668407336215e417393.
> chore: Revert "chore: Bump xml2js and aws-sdk (#41)"

- package-lock.json
- package.json
Addresses this: https://github.com/cloudscape-design/browser-test-tools/security/dependabot/7
> chore: Bump xml2js and aws-sdk

- .husky/commit-msg
- .husky/pre-commit
- .husky/prepare-commit-msg
Syncing husky folder with changes made in components: https://github.com/cloudscape-design/components/commit/182daec9b54abdf15e5b1569e7ff578041348ac0
> chore: Replace &> operator in husky scripts for wider shell compatibility

- __mocks__/aws-sdk/clients/devicefarm.js
- package-lock.json
- package.json
- src/browsers/browser-creator.ts
- src/browsers/browserstack.ts
- src/browsers/devicefarm.ts
- src/page-objects/base.ts
- test/browser.test.ts
- test/browsers/browserstack.test.ts
- test/browsers/devicefarm-mobile.test.ts
- test/browsers/devicefarm.test.ts
- test/browsers/wdio-mock.ts
- test/compare-images.test.ts
- test/full-page-screenshot.test.ts
- test/image-utils.test.ts
- test/page-object.test.ts
- test/use-browser.test.ts
- test/utils/config.ts
- test/utils/setup-local-driver.ts
- test/utils/start-chromedriver.ts
- test/utils/stop-chromedriver.ts
- tsconfig.test.json
A continuation of #52, with my additions
> chore: Convert tests to typescript

- src/browsers/browser-creator.ts
- test/browsers/devicefarm-mobile.test.ts
- test/browsers/wdio-mock.ts
> chore: Make sure the iOS Safari tab bar is always at the bottom

- package.json
> chore: Add explicit files list to package json

- vite.config.ts
An attempt to fix flaky tests
Multiple successful retries in a row:
* https://github.com/cloudscape-design/browser-test-tools/actions/runs/9545443685/job/26306190317?pr=84
* https://github.com/cloudscape-design/browser-test-tools/actions/runs/9545690695/job/26306994684?pr=84
* https://github.com/cloudscape-design/browser-test-tools/actions/runs/9545717532/job/26307084631?pr=84
> chore: Limit tests concurrency

- package-lock.json
- package.json
This reverts commit 6aa1a1536d0e950a99d40a9c70407773c83dbf0f.
*Description of changes:* Temporarily revert - dependencies not yet available internally.
> revert: Bump fast-xml-parser and @aws-sdk/client-device-farm (#92)

- src/page-objects/base.ts
- test/fixtures/test-page-object.html
- test/page-object.test.ts
- test/utils.test.ts
Used this twice already: https://github.com/cloudscape-design/components/pull/2499, https://github.com/cloudscape-design/components/pull/2567
Time to extract a proper util
> feat: Add runInsideIframe utility

- package-lock.json
- tsconfig.json
> chore: Upgrade dependencies

- src/page-objects/base.ts
- test/fixtures/test-page-object.html
- test/page-object.test.ts
Introducing a new helper to avoid the compatibility issue when migrating to WebdriverIO v9.
The utility is to be used here: https://github.com/cloudscape-design/components/pull/2735
> feat: Add isDisplayedInViewport page helper

- test/fixtures/compare-test.html
- test/fixtures/index.html
- test/fixtures/rounding-test.html
- test/fixtures/test-full-page-screenshot.html
- test/fixtures/test-page-object.html
- test/page-object.test.ts
Update doctype and metatags on the test pages to be in sync with our main environment: https://github.com/cloudscape-design/components/blob/8f5431afadbafa27c72ca1ea4012dca304513107/pages/app/index.html#L1-L6
> chore: Fix testing pages

- src/browsers/capabilities.ts
This reverts commit be1476baf6858391b689c345e566c5bdf28e2be7.
> revert: "chore: Show scrollbars in Chrome-based integration tests (#120)"

- package-lock.json
- package.json
Update vitest dependency to address https://github.com/cloudscape-design/browser-test-tools/security/dependabot/32
> chore: Update vitest

- .husky/commit-msg
- .husky/pre-commit
- .husky/prepare-commit-msg
- package-lock.json
- package.json
Upgrading in a similar way to https://github.com/cloudscape-design/components/pull/1984
Mostly just need a PR that can trigger the release flow.
> chore: Update husky version

- src/page-objects/base.ts
- test/page-object.test.ts
Offer an alternative to `waitForVisible`
> feat: Add waitForExist utility

- package-lock.json
- package.json
This reverts commit a82fa01bfd58d9e733dabbf99d86e4c8c9af7260.
> chore: Revert "chore: Upgrade 'wait-on' (#140)"
